### ISSUE TITLE
Shogunate Flavor

### ISSUE THREAD

**Issue by pinballwizard933** [Horthy/HPMP#21]
I would really like to see a shogunate formation of Japan result in a different outcome than an imperial victory. Here are my suggestions: 1- Allow Edo to remain the Capital without changing its name to Tokyo. 2 - there should be an event like with de Rosa victory in the Argentine Civil war offering the options for the government of the new Japan: 1 - "the empire is an outdated instution. Japan can only hope to repel the barbarians by trusting utterly in the military genius of the Shogun (military dictatorship) 2 - The traitorous Meiji Emperor has been crushed. The time has come for the Shogun

**Comment by pinballwizard933** [comment]
Continued - The time has come for the Shogun to ascend the chrysanthemum throne. Long live emperor Tokugawa! (Absolute monarchy) 3 - we have broken the shackles of tradition. Only by becoming a truly modern country can we hope to resist the west. Our governments shall follow the example of the united states of america. Never again will their gunboats threaten our ports! (Democracy)

**Comment by Horthy** [comment]
Thank you for contributing! (Sorry for the late reply, usually only Autist posts in here) Yes, the Edo thing makes complete sense. I'll see about the government thing, I don't know if Japan was ready or willing to immediately become a democracy, but the rest are good and realistic options.
